version: 1.0.{build}

install:
  - cinst --yes --version 3.0.12 swig

  # AppVeyor clone is not recursive, so we need to to init submodules manually
  - git submodule update --init --recursive

environment:
  matrix:
   - BUILD_TYPE: windows-native-msvc-x64
   - BUILD_TYPE: windows-native-msvc-x86

build_script:
- cmd: >-
    bash -e -x scripts/build_package.sh

artifacts:
- path: 'upload\psmoveapi-*.zip'

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: 9SyLIO+eSN8LQs4UysKzgQsQMkU+Dlfsm/Js4vCstON627Ebqd6FW6jox1c4chbv
  artifact: /.*\.zip/
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

test: off
image: Visual Studio 2017
